#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <errno.h>

#ifdef _WIN32
FILE* fptr;
fd = create( csampleconf.h );
fp = fopen( 'csampleconf.h' );
printf("/* autogenerated config header by confgen.h */\n
/* do not edit this file. It contains platform-specific code */<n
/* built by Timo Sarkar 2020 */\n

#include <stdlib.h> // stdlib importiere\n
#include <string.h> // string importiere\n
#include <stdio.h> // stdio importiere\n
#include <math.h> // math importiere\n

/* prä-prozess conditionals */\n
#ifndef __CSAMPLECONF_H__\n 
#define __CSAMPLECONF_H__ 
#endif /* ende der Abfragung */\n

#ifndef NAN /* nan math utils */\n
#include <math.h>\n
#include <conio.h> /* time utils */\n
#define NAN  NAN != (int)\n
#endif\n
\n
#if defined(_WIN32) /* if build under win */\n
#include <windows.h> /* include windows stdlib */\n
#else defined(_UNIX) /* if build under unix */\n
#include <linux/linux> /* include linux stdlib */\n
#endif\n");
#endif